### ISSUE TITLE
compile issue on Wily

### ISSUE THREAD

**Issue by 9000h** [chriszero/vdr-plugin-plex#4]
root@satip:/usr/src/vdr/vdr-2.3.1/PLUGINS/src/plex# make
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -std=c++11 -c -DLIBSKINDESIGNERAPIVERSION='"0.1.0"' -DPLUGIN_NAME_I18N='"plex"' -DPLUGIN='"plex"' -D_GNU_SOURCE -DSKINDESIGNER  -DGIT_REV='"0.3.0-17-geef71c6"' -I/usr/local/include  -o Plexservice.o Plexservice.cpp
Plexservice.cpp: In static member function ‘static std::__cxx11::string plexclient::Plexservice::GetUniversalTranscodeUrl(plexclient::Video*, int, plexclient::PlexServer*, bool)’:
Plexservice.cpp:256:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("protocol", "hls");
                ^
Plexservice.cpp:257:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("includeCodecs", "1");
                ^
Plexservice.cpp:259:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("directPlay", "0");
                ^
Plexservice.cpp:260:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("directStream", "1");
                ^
Plexservice.cpp:261:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("subtitles", "burn");
                ^
Plexservice.cpp:262:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("audioBoost", "100");
                ^
Plexservice.cpp:266:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("protocol", "http");
                ^
Plexservice.cpp:268:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("X-Plex-Client-Identifier", Config::GetInstance().GetUUID());
                ^
Plexservice.cpp:269:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("X-Plex-Product", "Chromecast");
                ^
Plexservice.cpp:270:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("X-Plex-Platform", "Chromecast");
                ^
Plexservice.cpp:271:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("X-Plex-Token", pSrv->GetAuthToken());
                ^
Plexservice.cpp:280:15: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
  transcodeUri.addQueryParameter("path", pathUri.toString());
               ^
Plexservice.cpp:281:15: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
  transcodeUri.addQueryParameter("mediaIndex", "0");
               ^
Plexservice.cpp:282:15: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
  transcodeUri.addQueryParameter("partIndex", "0");
               ^
Plexservice.cpp:283:15: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
  transcodeUri.addQueryParameter("offset", std::to_string(offset) );
               ^
Plexservice.cpp:284:15: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
  transcodeUri.addQueryParameter("fastSeek", "1");
               ^
Plexservice.cpp:288:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("videoResolution", "1920x1080");
                ^
Plexservice.cpp:289:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("maxVideoBitrate", "20000");
                ^
Plexservice.cpp:290:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("videoQuality", "100");
                ^
Plexservice.cpp:292:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("videoResolution", "1280x720");
                ^
Plexservice.cpp:293:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("maxVideoBitrate", "8000");
                ^
Plexservice.cpp:294:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("videoQuality", "100");
                ^
Plexservice.cpp:296:15: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
  transcodeUri.addQueryParameter("session", Config::GetInstance().GetUUID()); // TODO: generate Random SessionID
               ^
Plexservice.cpp:300:16: error: ‘class Poco::URI’ has no member named ‘addQueryParameter’
   transcodeUri.addQueryParameter("X-Plex-Client-Profile-Extra", "add-transcode-target-audio-codec(type=videoProfile&context=streaming&protocol=hls&audioCodec=ac3)");
                ^
Makefile:119: recipe for target 'Plexservice.o' failed
make: *** [Plexservice.o] Error 1

**Comment by chriszero** [comment]
Your libpoco is to old.

**Comment by 9000h** [comment]
ok will try with the 1.6.1 from yavdr

**Comment by 9000h** [comment]
works
