### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by utiltiy** [chriszero/vdr-plugin-plex#5]
Sollte das nicht "pDetailView" lauten anstatt "pDetailsView"?

` +	if (state != osEnd && m_pDetailsView && m_pDetailGrid->DrawTime()) m_pDetailGrid->Flush();`

**Comment by chriszero** [comment]
Ja, hast recht.
Funktioniert aber weil beide immer gleichzeitig auf Null sind.
Ging mir beim Testen durch die Lappen, hat ja den gewünschten Effekt gehabt. ;-)
Ich korrigiere das noch

**Comment by chriszero** [comment]
gefixt
